# !!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!
# First create a helper toggle button: input_boolean.toggle_light_switch

- id: '1644115300952'
  alias: 'Light Switch Replacement: Rotary Encoder Clockwise Master Bedroom'
  description: 'Increase volume of speakers that are currently playing something OR the bedroom ligt brightness. Toggling between these is done by pushing the rotary encoder button.'
  trigger:
  - platform: state
    entity_id: sensor.rotary_encoder_light_switch
  condition:
  - condition: state
    entity_id: binary_sensor.rotary_encoder_master_bedroom
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.toggle_light_switch
        state: 'on'
      sequence:
      - choose:
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.bathroom_speaker
              state: playing
            - condition: state
              entity_id: media_player.living_room_speaker
              state: playing
            - condition: state
              entity_id: media_player.master_bedroom_speaker
              state: playing
          sequence:
          - service: media_player.volume_up
            data: {}
            target:
              entity_id:
              - media_player.bathroom_speaker
              - media_player.living_room_speaker
              - media_player.master_bedroom_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.bathroom_speaker
              state: playing
            - condition: state
              entity_id: media_player.living_room_speaker
              state: playing
          sequence:
          - service: media_player.volume_up
            data: {}
            target:
              entity_id:
              - media_player.bathroom_speaker
              - media_player.living_room_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.living_room_speaker
              state: playing
            - condition: state
              entity_id: media_player.master_bedroom_speaker
              state: playing
          sequence:
          - service: media_player.volume_up
            data: {}
            target:
              entity_id:
              - media_player.living_room_speaker
              - media_player.master_bedroom_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.bathroom_speaker
              state: playing
            - condition: state
              entity_id: media_player.master_bedroom_speaker
              state: playing
          sequence:
          - service: media_player.volume_up
            data: {}
            target:
              entity_id:
              - media_player.bathroom_speaker
              - media_player.master_bedroom_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.bathroom_speaker
              state: playing
          sequence:
          - service: media_player.volume_up
            data: {}
            target:
              entity_id:
              - media_player.bathroom_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.living_room_speaker
              state: playing
          sequence:
          - service: media_player.volume_up
            data: {}
            target:
              entity_id:
              - media_player.living_room_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.master_bedroom_speaker
              state: playing
          sequence:
          - service: media_player.volume_up
            data: {}
            target:
              entity_id:
              - media_player.master_bedroom_speaker
        default: []
    default:
    - service: light.turn_on
      data:
        brightness_step_pct: 10
      target:
        entity_id: light.master_bedroom_lights
  mode: single
- id: '1644115762025'
  alias: 'Light Switch Replacement: Rotary Encoder Anti-Clockwise Master Bedroom'
  description: 'Decrease volume of speakers that are currently playing something OR the bedroom ligt brightness. Toggling between these is done by pushing the rotary encoder button.'
  trigger:
  - platform: state
    entity_id: sensor.rotary_encoder_light_switch
  condition:
  - condition: state
    entity_id: binary_sensor.rotary_encoder_master_bedroom
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.toggle_light_switch
        state: 'on'
      sequence:
      - choose:
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.bathroom_speaker
              state: playing
            - condition: state
              entity_id: media_player.living_room_speaker
              state: playing
            - condition: state
              entity_id: media_player.master_bedroom_speaker
              state: playing
          sequence:
          - service: media_player.volume_down
            data: {}
            target:
              entity_id:
              - media_player.bathroom_speaker
              - media_player.living_room_speaker
              - media_player.master_bedroom_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.bathroom_speaker
              state: playing
            - condition: state
              entity_id: media_player.living_room_speaker
              state: playing
          sequence:
          - service: media_player.volume_down
            data: {}
            target:
              entity_id:
              - media_player.bathroom_speaker
              - media_player.living_room_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.living_room_speaker
              state: playing
            - condition: state
              entity_id: media_player.master_bedroom_speaker
              state: playing
          sequence:
          - service: media_player.volume_down
            data: {}
            target:
              entity_id:
              - media_player.living_room_speaker
              - media_player.master_bedroom_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.bathroom_speaker
              state: playing
            - condition: state
              entity_id: media_player.master_bedroom_speaker
              state: playing
          sequence:
          - service: media_player.volume_down
            data: {}
            target:
              entity_id:
              - media_player.bathroom_speaker
              - media_player.master_bedroom_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.bathroom_speaker
              state: playing
          sequence:
          - service: media_player.volume_down
            data: {}
            target:
              entity_id:
              - media_player.bathroom_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.living_room_speaker
              state: playing
          sequence:
          - service: media_player.volume_down
            data: {}
            target:
              entity_id:
              - media_player.living_room_speaker
        - conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: media_player.master_bedroom_speaker
              state: playing
          sequence:
          - service: media_player.volume_down
            data: {}
            target:
              entity_id:
              - media_player.master_bedroom_speaker
        default: []
    default:
    - service: light.turn_on
      data:
        brightness_step_pct: -10
      target:
        entity_id: light.master_bedroom_lights
  mode: single
- id: '1644115937050'
  alias: 'Light Switch Replacement: Top Left'
  description: 'Toggle the bedroom lights.'
  trigger:
  - platform: state
    entity_id: binary_sensor.capacitive_touch_top_left_light_switch
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.master_bedroom_lights
        state: 'on'
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.master_bedroom_lights
    default:
    - service: script.scene_room_tibo_warm_white
      data: {}
  mode: single
- id: '1644115937050'
  alias: 'Light Switch Replacement: Top Right'
  description: 'Open or close the curtains.'
  trigger:
  - platform: state
    entity_id: binary_sensor.capacitive_touch_top_right_light_switch
    to: 'on'
  condition: []
  action:
  - service: script.blinds_toggle_open_close
    data: {}
  mode: single
- id: '1644116037934'
  alias: 'Light Switch Replacement: Bot Left'
  description: 'Toggle the downstairs lights.'
  trigger:
  - platform: state
    entity_id: binary_sensor.capacitive_touch_bot_left_light_switch
    to: 'on'
  condition: []
  action:
  - service: script.toggle_lights_for_mqtt_alarm
    data: {}
  mode: single
- id: '1644116055199'
  alias: 'Light Switch Replacement: Bot Right'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.capacitive_touch_bot_right_light_switch
    to: 'on'
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.master_bedroom_speaker
        attribute: media_content_id
        state: http://progressive-audio.lwc.vrtcdn.be/content/fixed/11_11niws-snip_hi.mp3
      sequence:
      - service: media_player.turn_off
        data: {}
        target:
          entity_id: media_player.master_bedroom_speaker
    default:
    - service: script.radio_nieuwsupdate_master_bedroom_no_delay
      data: {}
  mode: single
- id: '1644116395471'
  alias: 'Light Switch Replacement: Top Right'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.capacitive_touch_top_right_light_switch
    to: 'on'
  condition: []
  action:
  - service: script.blinds_toggle_open_close
    data: {}
  mode: single
- id: '1644245853485'
  alias: 'Light Switch Replacement: Toggle button rotary endcoder'
  description: ''
  use_blueprint:
    path: slashback/trigger-different-actions-on-a-single-double-or-double-click-on-a-binary-sensor.yaml
    input:
      switch_id: binary_sensor.toggle_button_light_switch
      delay: 1
      short_click_action:
      - service: input_boolean.toggle
        data: {}
        target:
          entity_id: input_boolean.toggle_light_switch
      long_click_action:
      - service: script.turn_everything_off
        data: {}
      double_click_action: []